# Generated by Django 4.1.7 on 2023-03-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_id',
            new_name='employee_department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='employee_salary',
        ),
    ]
